GPU: [0]

VERBOSE: True


VAL_FREQ: 1
SAVE_MODEL_FREQ: 20

DATASET: 'DVD'

MODEL:
  MODE: 'RFFNet'
  SESSION: 'ps128_bs16'
  RESUME: False
  RESUME_PATH: './checkpoints/RFFNet/DVD/model_best.pth'
  NUM_EPOCHS: 80
  TRAIN_PS: 128
  TRAIN_DIR: './dataset/DVD/train' # path of training data
  SAVE_DIR: './checkpoints'          # path to save models and images

NETWORK:
  guid_c: 1
  n_feat: 64
  scale_unetfeats: 32

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  LR_INITIAL: !!float 2e-4
  LR_MIN: !!float 1e-6

TEST:
  TEST_DIR: './dataset/DVD/test'
  MODEL: './checkpoints/RFFNet/DVD/model_best_1.pth'
  SIGMA: 2
  VIS_DIR: './results/RFFNet/DVD/visTestResults/'

TEST_REAL:
  TEST_DIR: './dataset/DVD/real'
  MODEL: './checkpoints/RFFNet/DVD/model_best_1.pth'
  VIS_DIR: './results/RFFNet/DVD/visRealResults/'

