GPU: [0]

VERBOSE: True


VAL_FREQ: 20
SAVE_MODEL_FREQ: 1000

DATASET: 'FAID'

MODEL:
  MODE: 'RFFNet'
  SESSION: 'ps128_bs16'
  RESUME: False
  RESUME_PATH: './checkpoints/RFFNet/FAID/model_best.pth'
  NUM_EPOCHS: 1500
  TRAIN_PS: 128
  TRAIN_DIR: './dataset/FAID/train' # path of training data
  SAVE_DIR: './checkpoints'          # path to save models and images
ABLATION:
NETWORK:
  guid_c: 3
  n_feat: 64
  scale_unetfeats: 32

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  LR_INITIAL: !!float 2e-4
  LR_MIN: !!float 1e-6

TEST:
  TEST_DIR: './dataset/FAID/test'
  MODEL: './checkpoints/RFFNet/FAID/model_best.pth'
  SIGMA: 25
  VIS_DIR: './results/RFFNet/FAID/visTestResults/'
